- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Verify MySQL installation
  command: mysql --version
  register: mysql_output

- name: Show MySQL version
  debug:
    var: mysql_output.stdout


